<?php

 echo "<div class='content'>";
  echo "<table>";
   echo "<tr>";
   echo "<td>";
    echo "<img class='image1' src=''/>";
    echo "</td>";
    echo "<td>";
    echo "<h2 class='title1'></h2>";
    echo "<p class='description1'></p>";
    echo "<p class='genre1'></p>";
    echo "<p class='platform1'></p>";
    echo "<p class='publisher1'></p>";
    echo "<p class='developer1'></p>";
    echo "<p class='release1'></p>";
    echo "</td>";
    echo "</tr>";

echo "<tr>";
echo "<td>";
echo "<img class='image2' src=''/>";
echo "</td>";
echo "<td>";
echo "<h2 class='title2'></h2>";
echo "<p class='description2'></p>";
echo "<p class='genre2'></p>";
echo "<p class='platform2'></p>";
echo "<p class='publisher2'></p>";
echo "<p class='developer2'></p>";
echo "<p class='release2'></p>";
echo "</td>";
echo "</tr>";

echo "<tr>";
echo "<td>";
echo "<img class='image3' src=''/>";
echo "</td>";
echo "<td>";
echo "<h2 class='title3'></h2>";
echo "<p class='description3'></p>";
echo "<p class='genre3'></p>";
echo "<p class='platform3'></p>";
echo "<p class='publisher3'></p>";
echo "<p class='developer3'></p>";
echo "<p class='release3'></p>";
echo "</td>";
echo "</tr>";

echo "<tr>";
echo "<td>";
echo "<img class='image4' src=''/>";
echo "</td>";
echo "<td>";
echo "<h2 class='title4'></h2>";
echo "<p class='description4'></p>";
echo "<p class='genre4'></p>";
echo "<p class='platform4'></p>";
echo "<p class='publisher4'></p>";
echo "<p class='developer4'></p>";
echo "<p class='release4'></p>";
echo "</td>";
echo "</tr>";

echo "<tr>";
echo "<td>";
echo "<img class='image5' src=''/>";
echo "</td>";
echo "<td>";
echo "<h2 class='title5'></h2>";
echo "<p class='description5'></p>";
echo "<p class='genre5'></p>";
echo "<p class='platform5'></p>";
echo "<p class='publisher5'></p>";
echo "<p class='developer5'></p>";
echo "<p class='release5'></p>";
echo "</td>";
echo "</tr>";

echo "<tr>";
echo "<td>";
echo "<img class='image6' src=''/>";
echo "</td>";
echo "<td>";
echo "<h2 class='title6'></h2>";
echo "<p class='description6'></p>";
echo "<p class='genre6'></p>";
echo "<p class='platform6'></p>";
echo "<p class='publisher6'></p>";
echo "<p class='developer6'></p>";
echo "<p class='release6'></p>";
echo "</td>";
echo "</tr>";

echo "<tr>";
echo "<td>";
echo "<img class='image7' src=''/>";
echo "</td>";
echo "<td>";
echo "<h2 class='title7'></h2>";
echo "<p class='description7'></p>";
echo "<p class='genre7'></p>";
echo "<p class='platform7'></p>";
echo "<p class='publisher7'></p>";
echo "<p class='developer7'></p>";
echo "<p class='release7'></p>";
echo "</td>";
echo "</tr>";

echo "<tr>";
echo "<td>";
echo "<img class='image8' src=''/>";
echo "</td>";
echo "<td>";
echo "<h2 class='title8'></h2>";
echo "<p class='description8'></p>";
echo "<p class='genre8'></p>";
echo "<p class='platform8'></p>";
echo "<p class='publisher8'></p>";
echo "<p class='developer8'></p>";
echo "<p class='release8'></p>";
echo "</td>";
echo "</tr>";

echo "<tr>";
echo "<td>";
echo "<img class='image9' src=''/>";
echo "</td>";
echo "<td>";
echo "<h2 class='title9'></h2>";
echo "<p class='description9'></p>";
echo "<p class='genre9'></p>";
echo "<p class='platform9'></p>";
echo "<p class='publisher9'></p>";
echo "<p class='developer9'></p>";
echo "<p class='release9'></p>";
echo "</td>";
echo "</tr>";

echo "<tr>";
echo "<td>";
echo "<img class='image10' src=''/>";
echo "</td>";
echo "<td>";
echo "<h2 class='title10'></h2>";
echo "<p class='description10'></p>";
echo "<p class='genre10'></p>";
echo "<p class='platform10'></p>";
echo "<p class='publisher10'></p>";
echo "<p class='developer10'></p>";
echo "<p class='release10'></p>";
echo "</td>";
echo "</tr>";

echo "<tr>";
echo "<td>";
echo "<img class='image11' src=''/>";
echo "</td>";
echo "<td>";
echo "<h2 class='title11'></h2>";
echo "<p class='description11'></p>";
echo "<p class='genre11'></p>";
echo "<p class='platform11'></p>";
echo "<p class='publisher11'></p>";
echo "<p class='developer11'></p>";
echo "<p class='release11'></p>";
echo "</td>";
echo "</tr>";

echo "<tr>";
echo "<td>";
echo "<img class='image12' src=''/>";
echo "</td>";
echo "<td>";
echo "<h2 class='title12'></h2>";
echo "<p class='description12'></p>";
echo "<p class='genre12'></p>";
echo "<p class='platform12'></p>";
echo "<p class='publisher12'></p>";
echo "<p class='developer12'></p>";
echo "<p class='release12'></p>";
echo "</td>";
echo "</tr>";

echo "<tr>";
echo "<td>";
echo "<img class='image13' src=''/>";
echo "</td>";
echo "<td>";
echo "<h2 class='title13'></h2>";
echo "<p class='description13'></p>";
echo "<p class='genre13'></p>";
echo "<p class='platform13'></p>";
echo "<p class='publisher13'></p>";
echo "<p class='developer13'></p>";
echo "<p class='release13'></p>";
echo "</td>";
echo "</tr>";

echo "<tr>";
echo "<td>";
echo "<img class='image14' src=''/>";
echo "</td>";
echo "<td>";
echo "<h2 class='title14'></h2>";
echo "<p class='description14'></p>";
echo "<p class='genre14'></p>";
echo "<p class='platform14'></p>";
echo "<p class='publisher14'></p>";
echo "<p class='developer14'></p>";
echo "<p class='release14'></p>";
echo "</td>";
echo "</tr>";

echo "<tr>";
echo "<td>";
echo "<img class='image15' src=''/>";
echo "</td>";
echo "<td>";
echo "<h2 class='title15'></h2>";
echo "<p class='description15'></p>";
echo "<p class='genre15'></p>";
echo "<p class='platform15'></p>";
echo "<p class='publisher15'></p>";
echo "<p class='developer15'></p>";
echo "<p class='release15'></p>";
echo "</td>";
echo "</tr>";

echo "<tr>";
echo "<td>";
echo "<img class='image16' src=''/>";
echo "</td>";
echo "<td>";
echo "<h2 class='title16'></h2>";
echo "<p class='description16'></p>";
echo "<p class='genre16'></p>";
echo "<p class='platform16'></p>";
echo "<p class='publisher16'></p>";
echo "<p class='developer16'></p>";
echo "<p class='release16'></p>";
echo "</td>";
echo "</tr>";

echo "<tr>";
echo "<td>";
echo "<img class='image17' src=''/>";
echo "</td>";
echo "<td>";
echo "<h2 class='title17'></h2>";
echo "<p class='description17'></p>";
echo "<p class='genre17'></p>";
echo "<p class='platform17'></p>";
echo "<p class='publisher17'></p>";
echo "<p class='developer17'></p>";
echo "<p class='release17'></p>";
echo "</td>";
echo "</tr>";

echo "<tr>";
echo "<td>";
echo "<img class='image18' src=''/>";
echo "</td>";
echo "<td>";
echo "<h2 class='title18'></h2>";
echo "<p class='description18'></p>";
echo "<p class='genre18'></p>";
echo "<p class='platform18'></p>";
echo "<p class='publisher18'></p>";
echo "<p class='developer18'></p>";
echo "<p class='release18'></p>";
echo "</td>";
echo "</tr>";

echo "<tr>";
echo "<td>";
echo "<img class='image19' src=''/>";
echo "</td>";
echo "<td>";
echo "<h2 class='title19'></h2>";
echo "<p class='description19'></p>";
echo "<p class='genre19'></p>";
echo "<p class='platform19'></p>";
echo "<p class='publisher19'></p>";
echo "<p class='developer19'></p>";
echo "<p class='release19'></p>";
echo "</td>";
echo "</tr>";

echo "<tr>";
echo "<td>";
echo "<img class='image20' src=''/>";
echo "</td>";
echo "<td>";
echo "<h2 class='title20'></h2>";
echo "<p class='description20'></p>";
echo "<p class='genre20'></p>";
echo "<p class='platform20'></p>";
echo "<p class='publisher20'></p>";
echo "<p class='developer20'></p>";
echo "<p class='release20'></p>";
echo "</td>";
echo "</tr>";

    echo "</table>";



    echo "</div>";

 echo "<script src='script.js'></script>";
?>